xpcjsid.o: xpcjsid.cpp /usr/include/stdc-predef.h \
 ../../../../config/gcc_hidden.h ../../../../mozilla-config.h \
 xpcprivate.h ../../../../dist/include/system_wrappers/string.h \
 /usr/include/string.h \
 ../../../../dist/include/system_wrappers/features.h \
 /usr/include/features.h \
 ../../../../dist/include/system_wrappers/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/bits/wordsize.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
 ../../../../dist/include/system_wrappers/stddef.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h /usr/include/xlocale.h \
 /usr/include/x86_64-linux-gnu/bits/string3.h \
 ../../../../dist/include/system_wrappers/stdlib.h \
 /usr/include/c++/6/stdlib.h \
 ../../../../dist/include/system_wrappers/cstdlib \
 /usr/include/c++/6/cstdlib \
 /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/cpu_defines.h \
 /usr/include/stdlib.h /usr/include/x86_64-linux-gnu/bits/waitflags.h \
 /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
 ../../../../dist/include/system_wrappers/sys/types.h \
 /usr/include/x86_64-linux-gnu/sys/types.h \
 /usr/include/x86_64-linux-gnu/bits/types.h \
 /usr/include/x86_64-linux-gnu/bits/typesizes.h \
 ../../../../dist/include/system_wrappers/time.h /usr/include/time.h \
 ../../../../dist/include/system_wrappers/endian.h /usr/include/endian.h \
 /usr/include/x86_64-linux-gnu/bits/endian.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
 ../../../../dist/include/system_wrappers/sys/select.h \
 /usr/include/x86_64-linux-gnu/sys/select.h \
 /usr/include/x86_64-linux-gnu/bits/select.h \
 /usr/include/x86_64-linux-gnu/bits/sigset.h \
 /usr/include/x86_64-linux-gnu/bits/time.h \
 /usr/include/x86_64-linux-gnu/bits/select2.h \
 /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
 /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
 ../../../../dist/include/system_wrappers/alloca.h /usr/include/alloca.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib.h \
 ../../../../dist/include/system_wrappers/stdarg.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h \
 ../../../../dist/include/system_wrappers/math.h \
 /usr/include/c++/6/math.h /usr/include/c++/6/cmath \
 /usr/include/c++/6/bits/cpp_type_traits.h \
 /usr/include/c++/6/ext/type_traits.h /usr/include/math.h \
 /usr/include/x86_64-linux-gnu/bits/math-vector.h \
 /usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h \
 /usr/include/x86_64-linux-gnu/bits/huge_val.h \
 /usr/include/x86_64-linux-gnu/bits/huge_valf.h \
 /usr/include/x86_64-linux-gnu/bits/huge_vall.h \
 /usr/include/x86_64-linux-gnu/bits/inf.h \
 /usr/include/x86_64-linux-gnu/bits/nan.h \
 /usr/include/x86_64-linux-gnu/bits/mathdef.h \
 /usr/include/x86_64-linux-gnu/bits/mathcalls.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/xpcom-config.h \
 ../../../../dist/include/system_wrappers/prtypes.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/nspr/prcpucfg.h \
 ../../../../dist/include/nspr/obsolete/protypes.h \
 ../../../../dist/include/xpcom/nsError.h \
 ../../../../dist/include/xpcom/nsXPCOM.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/nsXPCOMCID.h \
 ../../../../dist/include/xpcom/nsAutoPtr.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/xpcom/nsXPCOM.h \
 ../../../../dist/include/xpcom/nsISupportsUtils.h \
 ../../../../dist/include/xpcom/nsISupportsBase.h \
 ../../../../dist/include/xpcom/nsID.h \
 ../../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../../dist/include/system_wrappers/prthread.h \
 ../../../../dist/include/nspr/prthread.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/nspr/prinrval.h \
 ../../../../dist/include/system_wrappers/pratom.h \
 ../../../../dist/include/nspr/pratom.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../../dist/include/xpcom/nsCycleCollector.h \
 ../../../../dist/include/xpcom/nsCycleCollectionParticipant.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsrootidl.h \
 ../../../../dist/include/system_wrappers/prtime.h \
 ../../../../dist/include/nspr/prtime.h \
 ../../../../dist/include/nspr/prlong.h \
 ../../../../dist/include/xpcom/nsCycleCollector.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/xpcom/nsIServiceManagerObsolete.h \
 ../../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../../dist/include/xpcom/nsIFactory.h \
 ../../../../dist/include/xpcom/nsIClassInfoImpl.h \
 ../../../../dist/include/xpcom/nsIClassInfo.h \
 ../../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../../dist/include/xpcom/nsIComponentRegistrar.h \
 ../../../../dist/include/xpcom/nsISupportsPrimitives.h \
 ../../../../dist/include/xpcom/nsIGenericFactory.h \
 ../../../../dist/include/xpcom/nsIModule.h \
 ../../../../dist/include/xpcom/nsMemory.h \
 ../../../../dist/include/xpcom/nsIMemory.h \
 ../../../../dist/include/xpconnect/nsIXPConnect.h \
 ../../../../dist/include/xpconnect/xpccomponents.h \
 ../../../../dist/include/xpconnect/xpcexception.h \
 ../../../../dist/include/xpcom/nsIException.h \
 ../../../../dist/include/xpcom/nsIProgrammingLanguage.h \
 ../../../../dist/include/xpconnect/xpcjsid.h \
 ../../../../dist/include/xpconnect/nsIScriptableInterfaces.h \
 ../../../../dist/include/xpcom/nsIInterfaceInfoManager.h \
 ../../../../dist/include/xpcom/nsIInterfaceInfo.h \
 ../../../../dist/include/xpcom/nsIEnumerator.h \
 ../../../../dist/include/xpcom/nsISimpleEnumerator.h \
 ../../../../dist/include/xpcom/nsIExceptionService.h \
 ../../../../dist/include/xpcom/nsIVariant.h \
 ../../../../dist/include/js/jspubtd.h \
 ../../../../dist/include/js/jstypes.h \
 ../../../../dist/include/js/jsautocfg.h \
 ../../../../dist/include/js/jsotypes.h \
 ../../../../dist/include/js/jscompat.h \
 ../../../../dist/include/js/jslong.h \
 ../../../../dist/include/js/jsproto.tbl \
 ../../../../dist/include/js/jsconfig.h \
 ../../../../dist/include/xpcom/xptinfo.h \
 ../../../../dist/include/xpcom/xpt_struct.h \
 ../../../../dist/include/xpcom/xpt_arena.h \
 ../../../../dist/include/xpconnect/nsAXPCNativeCallContext.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsIInterfaceInfo.h \
 ../../../../dist/include/xpconnect/nsIXPCScriptable.h \
 ../../../../dist/include/xpconnect/nsIXPCSecurityManager.h \
 ../../../../dist/include/xpconnect/nsIJSRuntimeService.h \
 ../../../../dist/include/xpcom/nsWeakReference.h \
 ../../../../dist/include/xpcom/nsIWeakReference.h \
 ../../../../dist/include/xpcom/nsIWeakReferenceUtils.h \
 ../../../../dist/include/xpcom/nsIModule.h \
 ../../../../dist/include/xpcom/nsAutoLock.h \
 ../../../../dist/include/system_wrappers/prlock.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/system_wrappers/prlog.h \
 ../../../../dist/include/nspr/prlog.h \
 ../../../../dist/include/system_wrappers/prcmon.h \
 ../../../../dist/include/nspr/prcmon.h \
 ../../../../dist/include/nspr/prmon.h \
 ../../../../dist/include/xpcom/nsXPTCUtils.h \
 ../../../../dist/include/xpcom/xptcall.h \
 ../../../../dist/include/xpcom/xptinfo.h \
 ../../../../dist/include/js/jsapi.h \
 ../../../../dist/include/system_wrappers/stdio.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 ../../../../dist/include/system_wrappers/wchar.h /usr/include/wchar.h \
 /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
 /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
 /usr/include/x86_64-linux-gnu/bits/stdio2.h \
 ../../../../dist/include/js/jspubtd.h \
 ../../../../dist/include/js/jsutil.h \
 ../../../../dist/include/js/jsdhash.h \
 ../../../../dist/include/js/jsprf.h \
 ../../../../dist/include/system_wrappers/prprf.h \
 ../../../../dist/include/nspr/prprf.h \
 ../../../../dist/include/nspr/prio.h \
 ../../../../dist/include/nspr/prtime.h \
 ../../../../dist/include/nspr/prinet.h \
 ../../../../dist/include/system_wrappers/sys/socket.h \
 /usr/include/x86_64-linux-gnu/sys/socket.h \
 ../../../../dist/include/system_wrappers/sys/uio.h \
 /usr/include/x86_64-linux-gnu/sys/uio.h \
 /usr/include/x86_64-linux-gnu/bits/uio.h \
 /usr/include/x86_64-linux-gnu/bits/socket.h \
 /usr/include/x86_64-linux-gnu/bits/socket_type.h \
 /usr/include/x86_64-linux-gnu/bits/sockaddr.h \
 /usr/include/x86_64-linux-gnu/asm/socket.h \
 /usr/include/asm-generic/socket.h \
 /usr/include/x86_64-linux-gnu/asm/sockios.h \
 /usr/include/asm-generic/sockios.h \
 /usr/include/x86_64-linux-gnu/bits/socket2.h \
 ../../../../dist/include/system_wrappers/netinet/in.h \
 /usr/include/netinet/in.h \
 ../../../../dist/include/system_wrappers/stdint.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h /usr/include/stdint.h \
 /usr/include/x86_64-linux-gnu/bits/wchar.h \
 /usr/include/x86_64-linux-gnu/bits/in.h \
 ../../../../dist/include/system_wrappers/arpa/inet.h \
 /usr/include/arpa/inet.h \
 ../../../../dist/include/system_wrappers/netdb.h /usr/include/netdb.h \
 /usr/include/rpc/netdb.h /usr/include/x86_64-linux-gnu/bits/siginfo.h \
 /usr/include/x86_64-linux-gnu/bits/netdb.h \
 ../../../../dist/include/js/jsinterp.h \
 ../../../../dist/include/js/jsprvtd.h \
 ../../../../dist/include/js/jsfun.h ../../../../dist/include/js/jsobj.h \
 ../../../../dist/include/js/jshash.h \
 ../../../../dist/include/js/jsopcode.h \
 ../../../../dist/include/js/jsopcode.tbl \
 ../../../../dist/include/js/jsscript.h \
 ../../../../dist/include/js/jsatom.h \
 ../../../../dist/include/js/jsdhash.h \
 ../../../../dist/include/js/jsapi.h ../../../../dist/include/js/jslock.h \
 ../../../../dist/include/system_wrappers/prcvar.h \
 ../../../../dist/include/nspr/prcvar.h \
 ../../../../dist/include/js/jscntxt.h \
 ../../../../dist/include/js/jsarena.h \
 ../../../../dist/include/js/jsclist.h ../../../../dist/include/js/jsgc.h \
 ../../../../dist/include/js/jsbit.h \
 ../../../../dist/include/js/jsinterp.h \
 ../../../../dist/include/js/jsregexp.h \
 ../../../../dist/include/js/jsstr.h \
 ../../../../dist/include/system_wrappers/ctype.h /usr/include/ctype.h \
 ../../../../dist/include/js/js.msg \
 ../../../../dist/include/js/jsdbgapi.h \
 ../../../../dist/include/js/jsgc.h xpcforwards.h xpclog.h \
 ../../../../dist/include/xpconnect/xpccomponents.h \
 ../../../../dist/include/xpconnect/xpcexception.h \
 ../../../../dist/include/xpconnect/xpcjsid.h \
 ../../../../dist/include/system_wrappers/prlong.h \
 ../../../../dist/include/nspr/prlong.h \
 ../../../../dist/include/system_wrappers/prmem.h \
 ../../../../dist/include/nspr/prmem.h \
 ../../../../dist/include/system_wrappers/prenv.h \
 ../../../../dist/include/nspr/prenv.h \
 ../../../../dist/include/system_wrappers/prclist.h \
 ../../../../dist/include/nspr/prclist.h \
 ../../../../dist/include/string/nsString.h \
 ../../../../dist/include/string/nsSubstring.h \
 ../../../../dist/include/string/nsAString.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/string/nsStringIterator.h \
 ../../../../dist/include/string/nsCharTraits.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/string/nsAlgorithm.h \
 ../../../../dist/include/string/string-template-def-unichar.h \
 ../../../../dist/include/string/nsTAString.h \
 ../../../../dist/include/string/string-template-undef.h \
 ../../../../dist/include/string/string-template-def-char.h \
 ../../../../dist/include/string/nsSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstring.h \
 ../../../../dist/include/string/nsDependentSubstring.h \
 ../../../../dist/include/string/nsTDependentSubstring.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/system_wrappers/new /usr/include/c++/6/new \
 /usr/include/c++/6/exception \
 /usr/include/c++/6/bits/atomic_lockfree_defines.h \
 /usr/include/c++/6/bits/exception_ptr.h \
 /usr/include/c++/6/bits/exception_defines.h \
 /usr/include/c++/6/bits/nested_exception.h \
 /usr/include/c++/6/bits/move.h /usr/include/c++/6/bits/concept_check.h \
 /usr/include/c++/6/type_traits \
 ../../../../dist/include/string/nsTString.h \
 ../../../../dist/include/string/nsDependentString.h \
 ../../../../dist/include/string/nsTDependentString.h \
 ../../../../dist/include/string/nsLiteralString.h \
 ../../../../dist/include/string/nsPromiseFlatString.h \
 ../../../../dist/include/string/nsTPromiseFlatString.h \
 ../../../../dist/include/system_wrappers/plhash.h \
 ../../../../dist/include/nspr/plhash.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/string/nsXPIDLString.h \
 ../../../../dist/include/xpcom/nsThreadUtils.h \
 ../../../../dist/include/system_wrappers/prinrval.h \
 ../../../../dist/include/nspr/prinrval.h \
 ../../../../dist/include/xpcom/nsIThreadManager.h \
 ../../../../dist/include/xpcom/nsIThread.h \
 ../../../../dist/include/xpcom/nsIEventTarget.h \
 ../../../../dist/include/xpcom/nsIRunnable.h \
 ../../../../dist/include/xpcom/nsStringGlue.h \
 ../../../../dist/include/xpconnect/nsIJSContextStack.h \
 ../../../../dist/include/xpcom/nsDeque.h \
 ../../../../dist/include/xpcom/nsVoidArray.h \
 ../../../../dist/include/xpcom/nsIConsoleService.h \
 ../../../../dist/include/xpcom/nsIConsoleListener.h \
 ../../../../dist/include/xpcom/nsIConsoleMessage.h \
 ../../../../dist/include/xpconnect/nsIScriptError.h \
 ../../../../dist/include/xpcom/nsVariant.h \
 ../../../../dist/include/xpcom/nsIVariant.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/xpcom/nsIPropertyBag.h \
 ../../../../dist/include/xpcom/nsIProperty.h \
 ../../../../dist/include/xpcom/nsSupportsArray.h \
 ../../../../dist/include/xpcom/nsISupportsArray.h \
 ../../../../dist/include/xpcom/nsICollection.h \
 ../../../../dist/include/xpcom/nsISerializable.h \
 ../../../../dist/include/xpcom/nsTArray.h \
 ../../../../dist/include/xpcom/nsQuickSort.h \
 ../../../../dist/include/xpcom/nsBaseHashtable.h \
 ../../../../dist/include/xpcom/nsTHashtable.h \
 ../../../../dist/include/xpcom/pldhash.h \
 ../../../../dist/include/xpcom/nsHashKeys.h \
 ../../../../dist/include/xpcom/nsIHashable.h \
 ../../../../dist/include/xpcom/nsCRTGlue.h \
 ../../../../dist/include/xpconnect/nsIXPCScriptNotify.h \
 ../../../../dist/include/dom/nsIScriptObjectPrincipal.h \
 ../../../../dist/include/caps/nsIPrincipal.h \
 ../../../../dist/include/caps/nsISecurityCheckedComponent.h \
 ../../../../dist/include/xpcom/nsIThreadInternal.h \
 ../../../../dist/include/caps/nsIScriptSecurityManager.h xpcinlines.h \
 xpcmaps.h ../../../../dist/include/xpconnect/xpc_map_end.h
