nsXULPrototypeDocument.o: nsXULPrototypeDocument.cpp \
 /usr/include/stdc-predef.h ../../../../config/gcc_hidden.h \
 ../../../../mozilla-config.h nsXULPrototypeDocument.h \
 ../../../../dist/include/xpcom/nsAutoPtr.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/xpcom-config.h \
 ../../../../dist/include/system_wrappers/prtypes.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/nspr/prcpucfg.h \
 ../../../../dist/include/system_wrappers/stddef.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h \
 ../../../../dist/include/nspr/obsolete/protypes.h \
 ../../../../dist/include/system_wrappers/sys/types.h \
 /usr/include/x86_64-linux-gnu/sys/types.h \
 ../../../../dist/include/system_wrappers/features.h \
 /usr/include/features.h \
 ../../../../dist/include/system_wrappers/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/bits/wordsize.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
 /usr/include/x86_64-linux-gnu/bits/types.h \
 /usr/include/x86_64-linux-gnu/bits/typesizes.h \
 ../../../../dist/include/system_wrappers/time.h /usr/include/time.h \
 ../../../../dist/include/system_wrappers/endian.h /usr/include/endian.h \
 /usr/include/x86_64-linux-gnu/bits/endian.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
 ../../../../dist/include/system_wrappers/sys/select.h \
 /usr/include/x86_64-linux-gnu/sys/select.h \
 /usr/include/x86_64-linux-gnu/bits/select.h \
 /usr/include/x86_64-linux-gnu/bits/sigset.h \
 /usr/include/x86_64-linux-gnu/bits/time.h \
 /usr/include/x86_64-linux-gnu/bits/select2.h \
 /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
 /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
 ../../../../dist/include/xpcom/nsError.h \
 ../../../../dist/include/xpcom/nsXPCOM.h \
 ../../../../dist/include/xpcom/nsXPCOMCID.h \
 ../../../../dist/include/xpcom/nsISupportsUtils.h \
 ../../../../dist/include/xpcom/nsISupportsBase.h \
 ../../../../dist/include/xpcom/nsID.h \
 ../../../../dist/include/system_wrappers/string.h /usr/include/string.h \
 /usr/include/xlocale.h /usr/include/x86_64-linux-gnu/bits/string3.h \
 ../../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../../dist/include/system_wrappers/prthread.h \
 ../../../../dist/include/nspr/prthread.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/nspr/prinrval.h \
 ../../../../dist/include/system_wrappers/pratom.h \
 ../../../../dist/include/nspr/pratom.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../../dist/include/xpcom/nsCycleCollector.h \
 ../../../../dist/include/xpcom/nsCOMArray.h \
 ../../../../dist/include/xpcom/nsVoidArray.h \
 ../../../../dist/include/xpcom/nsStringGlue.h \
 ../../../../dist/include/string/nsString.h \
 ../../../../dist/include/string/nsSubstring.h \
 ../../../../dist/include/string/nsAString.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/string/nsStringIterator.h \
 ../../../../dist/include/string/nsCharTraits.h \
 ../../../../dist/include/system_wrappers/ctype.h /usr/include/ctype.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/string/nsAlgorithm.h \
 ../../../../dist/include/string/string-template-def-unichar.h \
 ../../../../dist/include/string/nsTAString.h \
 ../../../../dist/include/string/string-template-undef.h \
 ../../../../dist/include/string/string-template-def-char.h \
 ../../../../dist/include/string/nsSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstring.h \
 ../../../../dist/include/string/nsDependentSubstring.h \
 ../../../../dist/include/string/nsTDependentSubstring.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/system_wrappers/new /usr/include/c++/6/new \
 /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/cpu_defines.h \
 /usr/include/c++/6/exception \
 /usr/include/c++/6/bits/atomic_lockfree_defines.h \
 /usr/include/c++/6/bits/exception_ptr.h \
 /usr/include/c++/6/bits/exception_defines.h \
 /usr/include/c++/6/bits/nested_exception.h \
 /usr/include/c++/6/bits/move.h /usr/include/c++/6/bits/concept_check.h \
 /usr/include/c++/6/type_traits \
 ../../../../dist/include/string/nsTString.h \
 ../../../../dist/include/string/nsDependentString.h \
 ../../../../dist/include/string/nsTDependentString.h \
 ../../../../dist/include/string/nsLiteralString.h \
 ../../../../dist/include/string/nsPromiseFlatString.h \
 ../../../../dist/include/string/nsTPromiseFlatString.h \
 ../../../../dist/include/xpcom/nsMemory.h \
 ../../../../dist/include/xpcom/nsIMemory.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsrootidl.h \
 ../../../../dist/include/system_wrappers/prtime.h \
 ../../../../dist/include/nspr/prtime.h \
 ../../../../dist/include/nspr/prlong.h \
 ../../../../dist/include/system_wrappers/stdio.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 ../../../../dist/include/system_wrappers/wchar.h /usr/include/wchar.h \
 ../../../../dist/include/system_wrappers/stdarg.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h \
 /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
 /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
 /usr/include/x86_64-linux-gnu/bits/stdio2.h \
 ../../../../dist/include/system_wrappers/plhash.h \
 ../../../../dist/include/nspr/plhash.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsTArray.h \
 ../../../../dist/include/xpcom/nsQuickSort.h \
 ../../../../dist/include/dom/nsIScriptGlobalObjectOwner.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsISerializable.h \
 ../../../../dist/include/xpcom/nsCycleCollectionParticipant.h \
 nsXULDocument.h nsXULPrototypeCache.h \
 ../../../../layout/style/nsICSSStyleSheet.h \
 ../../../../layout/style/nsIStyleSheet.h \
 ../../../../dist/include/xpcom/nsIObserver.h \
 ../../../../dist/include/content/nsIXBLDocumentInfo.h \
 ../../../../dist/include/xuldoc/nsIXULPrototypeCache.h \
 ../../../../dist/include/xpcom/nsDataHashtable.h \
 ../../../../dist/include/xpcom/nsHashKeys.h \
 ../../../../dist/include/xpcom/nsIHashable.h \
 ../../../../dist/include/xpcom/pldhash.h \
 ../../../../dist/include/xpcom/nsCRTGlue.h \
 ../../../../dist/include/system_wrappers/stdlib.h \
 /usr/include/c++/6/stdlib.h \
 ../../../../dist/include/system_wrappers/cstdlib \
 /usr/include/c++/6/cstdlib /usr/include/stdlib.h \
 /usr/include/x86_64-linux-gnu/bits/waitflags.h \
 /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
 ../../../../dist/include/system_wrappers/alloca.h /usr/include/alloca.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib.h \
 ../../../../dist/include/xpcom/nsBaseHashtable.h \
 ../../../../dist/include/xpcom/nsTHashtable.h \
 ../../../../dist/include/system_wrappers/prlock.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/xpcom/nsInterfaceHashtable.h \
 ../../../../dist/include/xpcom/nsRefPtrHashtable.h \
 ../../../../dist/include/xpcom/nsAutoPtr.h \
 ../../../../dist/include/necko/nsURIHashKey.h \
 ../../../../dist/include/xpcom/pldhash.h \
 ../../../../dist/include/xpcom/nsCRT.h \
 ../../../../dist/include/system_wrappers/plstr.h \
 ../../../../dist/include/nspr/plstr.h \
 ../../../../dist/include/xpcom/nsCppSharedAllocator.h \
 ../../../../dist/include/xpcom/nsMemory.h \
 ../../../../dist/include/system_wrappers/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h \
 /usr/include/limits.h /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
 /usr/include/x86_64-linux-gnu/bits/local_lim.h \
 ../../../../dist/include/system_wrappers/linux/limits.h \
 /usr/include/linux/limits.h \
 /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
 /usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
 ../../../../dist/include/necko/nsIURI.h \
 ../../../xml/document/src/nsXMLDocument.h ../../../base/src/nsDocument.h \
 ../../../../dist/include/content/nsIDocument.h \
 ../../../../dist/include/content/nsINode.h \
 ../../../../dist/include/content/nsPIDOMEventTarget.h \
 ../../../../dist/include/widget/nsEvent.h \
 ../../../../dist/include/content/nsPropertyTable.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/nsTObserverArray.h \
 ../../../../dist/include/xpcom/nsTArray.h \
 ../../../../dist/include/content/nsINodeInfo.h \
 ../../../../dist/include/xpcom/nsIAtom.h \
 ../../../../dist/include/content/nsINameSpaceManager.h \
 ../../../../dist/include/xpcom/nsStringGlue.h \
 ../../../../dist/include/content/nsNodeInfoManager.h \
 ../../../../dist/include/dom/nsDOMString.h \
 ../../../../dist/include/string/nsAString.h \
 ../../../../dist/include/content/nsIDocumentObserver.h \
 ../../../../dist/include/content/nsIMutationObserver.h \
 ../../../../dist/include/necko/nsIURI.h \
 ../../../../dist/include/xpcom/nsWeakPtr.h \
 ../../../../dist/include/xpcom/nsIWeakReference.h \
 ../../../../dist/include/xpcom/nsIWeakReferenceUtils.h \
 ../../../../dist/include/xpcom/nsIWeakReferenceUtils.h \
 ../../../../dist/include/necko/nsILoadGroup.h \
 ../../../../dist/include/necko/nsIRequest.h \
 ../../../../dist/include/content/mozFlushType.h \
 ../../../../dist/include/layout/nsCompatibility.h \
 ../../../../dist/include/xpcom/nsWeakReference.h \
 ../../../../dist/include/xpcom/nsVoidArray.h \
 ../../../../dist/include/xpcom/nsHashSets.h \
 ../../../../dist/include/xpcom/nsDoubleHashtable.h \
 ../../../../dist/include/dom/nsIDOMXMLDocument.h \
 ../../../../dist/include/dom/nsIDOMDocument.h \
 ../../../../dist/include/dom/nsIDOMNode.h \
 ../../../../dist/include/dom/domstubs.h \
 ../../../../dist/include/dom/nsIDOM3Document.h \
 ../../../../dist/include/dom/nsIDOM3Node.h \
 ../../../../dist/include/dom/nsIDOMDocumentView.h \
 ../../../../dist/include/dom/nsIDOMDocumentXBL.h \
 ../../../../dist/include/dom/nsIDOMNSDocument.h \
 ../../../../dist/include/dom/nsIDOMNSDocumentStyle.h \
 ../../../../dist/include/dom/nsIDOMDocumentStyle.h \
 ../../../../dist/include/dom/nsIDOMDocumentRange.h \
 ../../../../dist/include/dom/nsIDOMDocumentTraversal.h \
 ../../../base/src/nsStubDocumentObserver.h \
 ../../../../dist/include/content/nsIDocumentObserver.h \
 ../../../../dist/include/dom/nsIDOM3EventTarget.h \
 ../../../../dist/include/dom/nsIDOMNSEventTarget.h \
 ../../../../dist/include/dom/nsIDOMStyleSheetList.h \
 ../../../../dist/include/dom/nsIScriptGlobalObject.h \
 ../../../../dist/include/xpcom/nsIProgrammingLanguage.h \
 ../../../../dist/include/dom/nsIDOMEventTarget.h \
 ../../../../dist/include/content/nsIContent.h \
 ../../../../dist/include/content/nsCaseTreatment.h \
 ../../../../dist/include/layout/nsChangeHint.h \
 ../../../../dist/include/content/nsIEventListenerManager.h \
 ../../../../dist/include/dom/nsIDOM3Node.h \
 ../../../../dist/include/caps/nsIPrincipal.h \
 ../../../../dist/include/htmlparser/nsIParser.h \
 ../../../../dist/include/necko/nsIStreamListener.h \
 ../../../../dist/include/necko/nsIRequestObserver.h \
 ../../../../dist/include/htmlparser/nsIDTD.h \
 ../../../../dist/include/htmlparser/nsITokenizer.h \
 ../../../../dist/include/xpcom/nsError.h \
 ../../../../dist/include/content/nsBindingManager.h \
 ../../../../dist/include/content/nsStubMutationObserver.h \
 ../../../../dist/include/content/nsXBLBinding.h \
 ../../../../dist/include/dom/nsIDOMNodeList.h \
 ../../../../layout/style/nsIStyleRuleProcessor.h \
 ../../../../dist/include/layout/nsPresContext.h \
 ../../../../dist/include/gfx/nsColor.h \
 ../../../../dist/include/gfx/gfxCore.h \
 ../../../../dist/include/gfx/nsCoord.h \
 ../../../../dist/include/xpcom/nsMathUtils.h \
 ../../../../dist/include/system_wrappers/math.h \
 /usr/include/c++/6/math.h /usr/include/c++/6/cmath \
 /usr/include/c++/6/bits/cpp_type_traits.h \
 /usr/include/c++/6/ext/type_traits.h /usr/include/math.h \
 /usr/include/x86_64-linux-gnu/bits/math-vector.h \
 /usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h \
 /usr/include/x86_64-linux-gnu/bits/huge_val.h \
 /usr/include/x86_64-linux-gnu/bits/huge_valf.h \
 /usr/include/x86_64-linux-gnu/bits/huge_vall.h \
 /usr/include/x86_64-linux-gnu/bits/inf.h \
 /usr/include/x86_64-linux-gnu/bits/nan.h \
 /usr/include/x86_64-linux-gnu/bits/mathdef.h \
 /usr/include/x86_64-linux-gnu/bits/mathcalls.h \
 ../../../../dist/include/system_wrappers/float.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/float.h \
 ../../../../dist/include/layout/nsIPresShell.h \
 ../../../../dist/include/gfx/nsRect.h \
 ../../../../dist/include/gfx/nsCoord.h \
 ../../../../dist/include/gfx/nsPoint.h \
 ../../../../dist/include/gfx/nsSize.h \
 ../../../../dist/include/gfx/nsMargin.h \
 ../../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../../dist/include/layout/nsCompatibility.h \
 ../../../../dist/include/layout/nsFrameManagerBase.h \
 ../../../../dist/include/content/mozFlushType.h \
 ../../../../dist/include/gfx/nsIDeviceContext.h \
 ../../../../dist/include/gfx/nsRect.h \
 ../../../../dist/include/widget/nsIWidget.h \
 ../../../../dist/include/widget/nsEvent.h \
 ../../../../dist/include/gfx/nsIRenderingContext.h \
 ../../../../dist/include/gfx/nsColor.h \
 ../../../../dist/include/thebes/gfxPoint.h \
 ../../../../dist/include/thebes/gfxTypes.h \
 ../../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../../dist/include/gfx/nsFont.h \
 ../../../../dist/include/xpcom/nsIWeakReference.h \
 ../../../../dist/include/gfx/nsITheme.h \
 ../../../../dist/include/locale/nsILanguageAtomService.h \
 ../../../../dist/include/xpcom/nsITimer.h \
 ../../../../dist/include/widget/nsIPrintSettings.h \
 ../../../../dist/include/gfx/nsMargin.h \
 ../../../base/src/nsPropertyTable.h ../../../base/src/nsGkAtoms.h \
 ../../../base/src/nsGkAtomList.h \
 ../../../../dist/include/layout/nsChangeHint.h \
 ../../../../dist/include/thebes/gfxRect.h \
 ../../../../dist/include/thebes/gfxPoint.h \
 ../../../../dist/include/webshell/nsILinkHandler.h \
 ../../../../dist/include/xpcom/nsClassHashtable.h \
 ../../../../dist/include/content/nsINodeInfo.h \
 ../../../../dist/include/dom/nsIDOMDocumentEvent.h \
 ../../../../dist/include/dom/nsIDOM3DocumentEvent.h \
 ../../../../dist/include/xpcom/nsHashtable.h \
 ../../../../dist/include/layout/nsIBoxObject.h \
 ../../../../dist/include/layout/nsPIBoxObject.h \
 ../../../../dist/include/dom/nsIScriptObjectPrincipal.h \
 ../../../base/src/nsScriptLoader.h \
 ../../../../dist/include/content/nsIScriptElement.h \
 ../../../../dist/include/content/nsIScriptLoaderObserver.h \
 ../../../../dist/include/necko/nsIStreamLoader.h \
 ../../../../layout/style/nsICSSLoader.h \
 ../../../../dist/include/string/nsSubstring.h \
 ../../../../dist/include/content/nsIRadioGroupContainer.h \
 ../../../../dist/include/content/nsIScriptEventManager.h \
 ../../../../dist/include/layout/nsILayoutHistoryState.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/necko/nsIRequest.h \
 ../../../base/src/nsStubMutationObserver.h \
 ../../../../dist/include/necko/nsIChannel.h \
 ../../../../layout/style/nsHTMLStyleSheet.h \
 ../../../../layout/style/nsIStyleRuleProcessor.h \
 ../../../../layout/style/nsIStyleRule.h \
 ../../../../layout/style/nsIHTMLCSSStyleSheet.h \
 ../../../../layout/style/nsStyleSet.h \
 ../../../../layout/style/nsICSSStyleSheet.h \
 ../../../../layout/style/nsRuleNode.h \
 ../../../../layout/style/nsStyleStruct.h \
 ../../../../layout/style/nsStyleCoord.h \
 ../../../../dist/include/layout/nsStyleConsts.h \
 ../../../../dist/include/layout/nsIPresShell.h \
 ../../../../layout/style/nsCSSValue.h \
 ../../../../layout/style/nsCSSProperty.h \
 ../../../../layout/style/nsCSSPropList.h \
 ../../../../dist/include/xpcom/nsCRTGlue.h \
 ../../../../dist/include/string/nsStringBuffer.h \
 ../../../../layout/style/nsStyleStructFwd.h \
 ../../../../layout/style/nsStyleStructList.h \
 ../../../events/src/nsXMLEventsManager.h \
 ../../../../dist/include/dom/nsIDOMEventListener.h \
 ../../../base/src/nsAttrAndChildArray.h ../../../base/src/nsAttrName.h \
 ../../../base/src/nsAttrValue.h \
 ../../../../dist/include/content/nsCaseTreatment.h \
 ../../../base/src/nsDOMAttributeMap.h \
 ../../../../dist/include/dom/nsIDOMNamedNodeMap.h \
 ../../../../dist/include/system_wrappers/prbit.h \
 ../../../../dist/include/nspr/prbit.h \
 ../../../../dist/include/content/nsPresShellIterator.h \
 ../../../../dist/include/content/nsIDocument.h \
 ../../../../dist/include/xpcom/nsIInterfaceRequestor.h \
 ../../../../dist/include/xpcom/nsIInterfaceRequestorUtils.h \
 ../../../../dist/include/necko/nsIChannelEventSink.h \
 ../../../../dist/include/dom/nsIScriptContext.h nsElementMap.h \
 ../../../../dist/include/xpcom/nsFixedSizeAllocator.h \
 ../../../../dist/include/system_wrappers/plarena.h \
 ../../../../dist/include/nspr/plarena.h \
 ../../../../dist/include/nspr/plarenas.h nsForwardReference.h \
 ../../../../dist/include/dom/nsIDOMXULCommandDispatcher.h \
 ../../../../dist/include/dom/nsIDOMXULDocument.h \
 ../../../../dist/include/xuldoc/nsIXULDocument.h \
 ../../../base/src/nsScriptLoader.h \
 ../../../../layout/style/nsICSSLoaderObserver.h \
 ../../../../dist/include/xpcom/nsIObjectInputStream.h \
 ../../../../dist/include/xpcom/nsIBinaryInputStream.h \
 ../../../../dist/include/xpcom/nsIInputStream.h \
 ../../../../dist/include/xpcom/nsIObjectOutputStream.h \
 ../../../../dist/include/xpcom/nsIBinaryOutputStream.h \
 ../../../../dist/include/xpcom/nsIOutputStream.h \
 ../../content/src/nsXULElement.h \
 ../../../../dist/include/dom/nsIDOMEvent.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/xpcom/nsIServiceManagerObsolete.h \
 ../../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../../dist/include/xpcom/nsIFactory.h \
 ../../../../dist/include/xuldoc/nsIControllers.h \
 ../../../../dist/include/xuldoc/nsIController.h \
 ../../../../layout/style/nsICSSParser.h \
 ../../../../dist/include/dom/nsIDOMElement.h \
 ../../../../dist/include/dom/nsIDOMXULElement.h \
 ../../../../dist/include/dom/nsIDOMXULMultSelectCntrlEl.h \
 ../../../../dist/include/dom/nsIDOMXULSelectCntrlEl.h \
 ../../../../dist/include/dom/nsIDOMXULControlElement.h \
 ../../../../dist/include/rdf/nsIRDFCompositeDataSource.h \
 ../../../../dist/include/rdf/nsIRDFDataSource.h \
 ../../../../dist/include/xpcom/nsISupportsArray.h \
 ../../../../dist/include/xpcom/nsICollection.h \
 ../../../../dist/include/xpcom/nsIEnumerator.h \
 ../../../../dist/include/xpcom/nsISimpleEnumerator.h \
 ../../../../dist/include/rdf/nsIRDFResource.h \
 ../../../../dist/include/rdf/nsIRDFNode.h \
 ../../../../dist/include/rdf/nsIRDFObserver.h \
 ../../../../dist/include/rdf/nsIRDFResource.h \
 ../../../../dist/include/dom/nsIScriptObjectOwner.h \
 ../../../../dist/include/dom/nsIScriptContext.h \
 ../../../../dist/include/xultmpl/nsIXULTemplateBuilder.h \
 ../../../../dist/include/content/nsIXBLService.h \
 ../../../../layout/style/nsICSSOMFactory.h \
 ../../../../dist/include/layout/nsLayoutCID.h \
 ../../../../dist/include/xpcom/nsIFactory.h \
 ../../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../base/src/nsAttrAndChildArray.h \
 ../../../base/src/nsGenericElement.h \
 ../../../../dist/include/dom/nsIDOMDocumentFragment.h \
 ../../../../dist/include/dom/nsIDOMNSElement.h \
 ../../../base/src/nsGenericDOMNodeList.h \
 ../../../../dist/include/content/nsContentUtils.h \
 ../../../../dist/include/js/jspubtd.h \
 ../../../../dist/include/js/jstypes.h \
 ../../../../dist/include/js/jsautocfg.h \
 ../../../../dist/include/js/jsotypes.h \
 ../../../../dist/include/js/jscompat.h \
 ../../../../dist/include/js/jslong.h \
 ../../../../dist/include/js/jsproto.tbl \
 ../../../../dist/include/js/jsconfig.h \
 ../../../../dist/include/js/jsnum.h \
 ../../../../dist/include/layout/nsIStatefulFrame.h \
 ../../../../dist/include/pref/nsIPref.h \
 ../../../../dist/include/pref/nsIPrefService.h \
 ../../../../dist/include/pref/nsIPrefBranch.h \
 ../../../../dist/include/content/nsContentList.h \
 ../../../../dist/include/dom/nsIDOMHTMLCollection.h \
 ../../../../dist/include/dom/nsDOMClassInfoID.h \
 ../../../../dist/include/xpcom/nsIClassInfo.h \
 ../../../../dist/include/dom/nsIScriptRuntime.h \
 ../../../base/src/nsNodeUtils.h \
 ../../../../dist/include/dom/nsIDOMNode.h \
 ../../../../dist/include/content/nsIMutationObserver.h \
 ../../../../dist/include/dom/nsDOMScriptObjectHolder.h \
 ../../../../dist/include/dom/nsIDOMScriptObjectFactory.h \
 ../../../../dist/include/dom/nsIDOMClassInfo.h \
 ../../../../dist/include/xpcom/nsIClassInfoImpl.h \
 ../../../../dist/include/xpcom/nsIClassInfo.h \
 ../../../../dist/include/dom/nsDOMClassInfoID.h \
 ../../../../dist/include/xpconnect/nsIXPCScriptable.h \
 ../../../../dist/include/xpconnect/nsIXPConnect.h \
 ../../../../dist/include/xpconnect/xpccomponents.h \
 ../../../../dist/include/xpconnect/xpcexception.h \
 ../../../../dist/include/xpcom/nsIException.h \
 ../../../../dist/include/xpconnect/xpcjsid.h \
 ../../../../dist/include/xpconnect/nsIScriptableInterfaces.h \
 ../../../../dist/include/xpcom/nsIInterfaceInfoManager.h \
 ../../../../dist/include/xpcom/nsIInterfaceInfo.h \
 ../../../../dist/include/xpcom/nsIExceptionService.h \
 ../../../../dist/include/xpcom/nsIVariant.h \
 ../../../../dist/include/xpcom/xptinfo.h \
 ../../../../dist/include/xpcom/xpt_struct.h \
 ../../../../dist/include/xpcom/xpt_arena.h \
 ../../../../dist/include/xpconnect/nsAXPCNativeCallContext.h \
 ../../../../dist/include/dom/nsDOMCID.h \
 ../../../../dist/include/content/nsIFrameLoader.h \
 ../../../../dist/include/caps/nsIScriptSecurityManager.h \
 ../../../../dist/include/xpconnect/nsIXPCSecurityManager.h \
 ../../../../dist/include/xpcom/nsIArray.h \
 ../../../../dist/include/js/jsapi.h \
 ../../../../dist/include/js/jspubtd.h \
 ../../../../dist/include/js/jsutil.h \
 ../../../../dist/include/xpcom/nsIConsoleService.h \
 ../../../../dist/include/xpcom/nsIConsoleListener.h \
 ../../../../dist/include/xpcom/nsIConsoleMessage.h \
 ../../../../dist/include/xpconnect/nsIScriptError.h \
 ../../../../dist/include/dom/nsIDOMScriptObjectFactory.h \
 ../../../../dist/include/dom/nsDOMCID.h \
 ../../../base/src/nsNodeInfoManager.h \
 ../../../../dist/include/dom/nsDOMJSUtils.h
