_xpidlgen/nsIXPCScriptable.xpt: \
	./nsIXPCScriptable.idl \
	../../../../dist/idl/nsISupports.idl \
	../../../../dist/idl/nsrootidl.idl \
	./nsIXPConnect.idl \
	../../../../dist/idl/nsIClassInfo.idl \
	./xpccomponents.idl \
	./xpcexception.idl \
	../../../../dist/idl/nsIException.idl \
	../../../../dist/idl/nsIProgrammingLanguage.idl \
	./xpcjsid.idl \
	../../../../dist/idl/nsIComponentManager.idl \
	./nsIScriptableInterfaces.idl \
	../../../../dist/idl/nsIInterfaceInfoManager.idl \
	../../../../dist/idl/nsIInterfaceInfo.idl \
	../../../../dist/idl/nsIEnumerator.idl \
	../../../../dist/idl/nsISimpleEnumerator.idl \
	../../../../dist/idl/nsIExceptionService.idl \
	../../../../dist/idl/nsIVariant.idl
