nsDownloadManager.o: nsDownloadManager.cpp /usr/include/stdc-predef.h \
 ../../../../config/gcc_hidden.h ../../../../mozilla-config.h \
 nsDownloadManager.h \
 ../../../../dist/include/downloads/nsIDownloadManager.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsrootidl.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/xpcom-config.h \
 ../../../../dist/include/system_wrappers/prtypes.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/nspr/prcpucfg.h \
 ../../../../dist/include/system_wrappers/stddef.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h \
 ../../../../dist/include/nspr/obsolete/protypes.h \
 ../../../../dist/include/system_wrappers/sys/types.h \
 /usr/include/x86_64-linux-gnu/sys/types.h \
 ../../../../dist/include/system_wrappers/features.h \
 /usr/include/features.h \
 ../../../../dist/include/system_wrappers/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/bits/wordsize.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
 /usr/include/x86_64-linux-gnu/bits/types.h \
 /usr/include/x86_64-linux-gnu/bits/typesizes.h \
 ../../../../dist/include/system_wrappers/time.h /usr/include/time.h \
 ../../../../dist/include/system_wrappers/endian.h /usr/include/endian.h \
 /usr/include/x86_64-linux-gnu/bits/endian.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
 ../../../../dist/include/system_wrappers/sys/select.h \
 /usr/include/x86_64-linux-gnu/sys/select.h \
 /usr/include/x86_64-linux-gnu/bits/select.h \
 /usr/include/x86_64-linux-gnu/bits/sigset.h \
 /usr/include/x86_64-linux-gnu/bits/time.h \
 /usr/include/x86_64-linux-gnu/bits/select2.h \
 /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
 /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
 ../../../../dist/include/xpcom/nsError.h \
 ../../../../dist/include/system_wrappers/prtime.h \
 ../../../../dist/include/nspr/prtime.h \
 ../../../../dist/include/nspr/prlong.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/xpcom/nsISupportsBase.h \
 ../../../../dist/include/xpcom/nsID.h \
 ../../../../dist/include/system_wrappers/string.h /usr/include/string.h \
 /usr/include/xlocale.h /usr/include/x86_64-linux-gnu/bits/string3.h \
 ../../../../dist/include/xpcom/nsISupportsUtils.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/xpcom/nsXPCOM.h \
 ../../../../dist/include/xpcom/nsXPCOMCID.h \
 ../../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../../dist/include/system_wrappers/prthread.h \
 ../../../../dist/include/nspr/prthread.h \
 ../../../../dist/include/nspr/prinrval.h \
 ../../../../dist/include/system_wrappers/pratom.h \
 ../../../../dist/include/nspr/pratom.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../../dist/include/xpcom/nsCycleCollector.h \
 ../../../../dist/include/downloads/nsIDownloadProgressListener.h \
 ../../../../dist/include/downloads/nsIDownload.h \
 ../../../../dist/include/uriloader/nsITransfer.h \
 ../../../../dist/include/uriloader/nsIWebProgressListener2.h \
 ../../../../dist/include/uriloader/nsIWebProgressListener.h \
 ../../../../dist/include/dom/nsIDOMDocument.h \
 ../../../../dist/include/dom/nsIDOMNode.h \
 ../../../../dist/include/dom/domstubs.h \
 ../../../../dist/include/dom/nsIDOMEventListener.h \
 ../../../../dist/include/uriloader/nsIWebProgressListener.h \
 ../../../../dist/include/uriloader/nsIWebProgressListener2.h \
 ../../../../dist/include/necko/nsIURI.h \
 ../../../../dist/include/webbrowserpersist/nsIWebBrowserPersist.h \
 ../../../../dist/include/necko/nsICancelable.h \
 ../../../../dist/include/xpcom/nsILocalFile.h \
 ../../../../dist/include/xpcom/nsIFile.h \
 ../../../../dist/include/xpcom/nsDirectoryServiceUtils.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsIServiceManagerObsolete.h \
 ../../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../../dist/include/xpcom/nsIFactory.h \
 ../../../../dist/include/xpcom/nsIProperties.h \
 ../../../../dist/include/system_wrappers/prio.h \
 ../../../../dist/include/nspr/prio.h \
 ../../../../dist/include/nspr/prtime.h \
 ../../../../dist/include/nspr/prinet.h \
 ../../../../dist/include/system_wrappers/sys/socket.h \
 /usr/include/x86_64-linux-gnu/sys/socket.h \
 ../../../../dist/include/system_wrappers/sys/uio.h \
 /usr/include/x86_64-linux-gnu/sys/uio.h \
 /usr/include/x86_64-linux-gnu/bits/uio.h \
 /usr/include/x86_64-linux-gnu/bits/socket.h \
 /usr/include/x86_64-linux-gnu/bits/socket_type.h \
 /usr/include/x86_64-linux-gnu/bits/sockaddr.h \
 /usr/include/x86_64-linux-gnu/asm/socket.h \
 /usr/include/asm-generic/socket.h \
 /usr/include/x86_64-linux-gnu/asm/sockios.h \
 /usr/include/asm-generic/sockios.h \
 /usr/include/x86_64-linux-gnu/bits/socket2.h \
 ../../../../dist/include/system_wrappers/netinet/in.h \
 /usr/include/netinet/in.h \
 ../../../../dist/include/system_wrappers/stdint.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h /usr/include/stdint.h \
 /usr/include/x86_64-linux-gnu/bits/wchar.h \
 /usr/include/x86_64-linux-gnu/bits/in.h \
 ../../../../dist/include/system_wrappers/arpa/inet.h \
 /usr/include/arpa/inet.h \
 ../../../../dist/include/system_wrappers/netdb.h /usr/include/netdb.h \
 /usr/include/rpc/netdb.h /usr/include/x86_64-linux-gnu/bits/siginfo.h \
 /usr/include/x86_64-linux-gnu/bits/netdb.h \
 ../../../../dist/include/system_wrappers/prlink.h \
 ../../../../dist/include/nspr/prlink.h \
 ../../../../dist/include/system_wrappers/stdio.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 ../../../../dist/include/system_wrappers/wchar.h /usr/include/wchar.h \
 ../../../../dist/include/system_wrappers/stdarg.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h \
 /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
 /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
 /usr/include/x86_64-linux-gnu/bits/stdio2.h \
 ../../../../dist/include/necko/nsIRequest.h \
 ../../../../dist/include/xpcom/nsIObserver.h \
 ../../../../dist/include/string/nsString.h \
 ../../../../dist/include/string/nsSubstring.h \
 ../../../../dist/include/string/nsAString.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/string/nsStringIterator.h \
 ../../../../dist/include/string/nsCharTraits.h \
 ../../../../dist/include/system_wrappers/ctype.h /usr/include/ctype.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/string/nsAlgorithm.h \
 ../../../../dist/include/string/string-template-def-unichar.h \
 ../../../../dist/include/string/nsTAString.h \
 ../../../../dist/include/string/string-template-undef.h \
 ../../../../dist/include/string/string-template-def-char.h \
 ../../../../dist/include/string/nsSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstring.h \
 ../../../../dist/include/string/nsDependentSubstring.h \
 ../../../../dist/include/string/nsTDependentSubstring.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/system_wrappers/new /usr/include/c++/6/new \
 /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/cpu_defines.h \
 /usr/include/c++/6/exception \
 /usr/include/c++/6/bits/atomic_lockfree_defines.h \
 /usr/include/c++/6/bits/exception_ptr.h \
 /usr/include/c++/6/bits/exception_defines.h \
 /usr/include/c++/6/bits/nested_exception.h \
 /usr/include/c++/6/bits/move.h /usr/include/c++/6/bits/concept_check.h \
 /usr/include/c++/6/type_traits \
 ../../../../dist/include/string/nsTString.h \
 ../../../../dist/include/string/nsDependentString.h \
 ../../../../dist/include/string/nsTDependentString.h \
 ../../../../dist/include/string/nsLiteralString.h \
 ../../../../dist/include/string/nsPromiseFlatString.h \
 ../../../../dist/include/string/nsTPromiseFlatString.h \
 ../../../../dist/include/xpcom/nsMemory.h \
 ../../../../dist/include/xpcom/nsIMemory.h \
 ../../../../dist/include/system_wrappers/plhash.h \
 ../../../../dist/include/nspr/plhash.h \
 ../../../../dist/include/intl/nsIStringBundle.h \
 ../../../../dist/include/xpcom/nsISimpleEnumerator.h \
 ../../../../dist/include/xpcom/nsISupportsPrimitives.h \
 ../../../../dist/include/mimetype/nsIMIMEInfo.h \
 ../../../../dist/include/storage/mozIStorageConnection.h \
 ../../../../dist/include/storage/mozIStorageStatement.h \
 ../../../../dist/include/storage/mozIStorageValueArray.h \
 ../../../../dist/include/storage/mozStorageHelper.h \
 ../../../../dist/include/storage/mozIStorageConnection.h \
 ../../../../dist/include/xpcom/nsCOMArray.h \
 ../../../../dist/include/xpcom/nsVoidArray.h \
 ../../../../dist/include/xpcom/nsStringGlue.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsArrayEnumerator.h \
 ../../../../dist/include/xpcom/nsAutoPtr.h \
 ../../../../dist/include/places/nsINavHistoryService.h \
 ../../../../dist/include/xpcom/nsIArray.h \
 ../../../../dist/include/xpcom/nsIObserverService.h \
 ../../../../dist/include/xpcom/nsITimer.h \
 ../../../../dist/include/uriloader/nsIWebProgress.h \
 ../../../../dist/include/rdf/nsIRDFService.h \
 ../../../../dist/include/rdf/nsIRDFResource.h \
 ../../../../dist/include/rdf/nsIRDFNode.h \
 ../../../../dist/include/rdf/nsIRDFLiteral.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/rdf/nsIRDFDataSource.h \
 ../../../../dist/include/xpcom/nsISupportsArray.h \
 ../../../../dist/include/xpcom/nsICollection.h \
 ../../../../dist/include/xpcom/nsISerializable.h \
 ../../../../dist/include/xpcom/nsIEnumerator.h \
 ../../../../dist/include/rdf/nsIRDFObserver.h \
 ../../../../dist/include/rdf/nsIRDFContainer.h \
 ../../../../dist/include/rdf/nsIRDFLiteral.h \
 ../../../../dist/include/rdf/rdf.h \
 ../../../../dist/include/xpcom/nsError.h \
 ../../../../dist/include/necko/nsNetUtil.h \
 ../../../../dist/include/necko/nsNetError.h \
 ../../../../dist/include/necko/nsNetCID.h \
 ../../../../dist/include/xpcom/nsStringGlue.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/necko/nsIURI.h \
 ../../../../dist/include/xpcom/nsIInputStream.h \
 ../../../../dist/include/xpcom/nsIOutputStream.h \
 ../../../../dist/include/necko/nsISafeOutputStream.h \
 ../../../../dist/include/necko/nsIStreamListener.h \
 ../../../../dist/include/necko/nsIRequestObserver.h \
 ../../../../dist/include/necko/nsIRequestObserverProxy.h \
 ../../../../dist/include/necko/nsISimpleStreamListener.h \
 ../../../../dist/include/necko/nsILoadGroup.h \
 ../../../../dist/include/xpcom/nsIInterfaceRequestor.h \
 ../../../../dist/include/xpcom/nsIInterfaceRequestorUtils.h \
 ../../../../dist/include/necko/nsIIOService.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/necko/nsIChannel.h \
 ../../../../dist/include/necko/nsIInputStreamChannel.h \
 ../../../../dist/include/necko/nsITransport.h \
 ../../../../dist/include/necko/nsIStreamTransportService.h \
 ../../../../dist/include/necko/nsIHttpChannel.h \
 ../../../../dist/include/necko/nsIDownloader.h \
 ../../../../dist/include/necko/nsIStreamLoader.h \
 ../../../../dist/include/necko/nsIUnicharStreamLoader.h \
 ../../../../dist/include/xpcom/nsIPipe.h \
 ../../../../dist/include/xpcom/nsIAsyncInputStream.h \
 ../../../../dist/include/xpcom/nsIAsyncOutputStream.h \
 ../../../../dist/include/necko/nsIProtocolHandler.h \
 ../../../../dist/include/necko/nsIFileProtocolHandler.h \
 ../../../../dist/include/xpcom/nsIStringStream.h \
 ../../../../dist/include/necko/nsIFileStreams.h \
 ../../../../dist/include/necko/nsIProtocolProxyService.h \
 ../../../../dist/include/necko/nsIProxyInfo.h \
 ../../../../dist/include/necko/nsIBufferedStreams.h \
 ../../../../dist/include/necko/nsIInputStreamPump.h \
 ../../../../dist/include/necko/nsIAsyncStreamCopier.h \
 ../../../../dist/include/xpcom/nsIPersistentProperties2.h \
 ../../../../dist/include/necko/nsISyncStreamListener.h \
 ../../../../dist/include/xpcom/nsInterfaceRequestorAgg.h \
 ../../../../dist/include/xpcom/nsIInterfaceRequestor.h \
 ../../../../dist/include/xpcom/nsInt64.h \
 ../../../../dist/include/system_wrappers/prlong.h \
 ../../../../dist/include/nspr/prlong.h \
 ../../../../dist/include/necko/nsINetUtil.h \
 ../../../../dist/include/necko/nsIAuthPrompt.h \
 ../../../../dist/include/necko/nsIAuthPrompt2.h \
 ../../../../dist/include/necko/nsIAuthPromptAdapterFactory.h \
 ../../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../../dist/include/necko/nsINestedURI.h \
 ../../../../dist/include/xpcom/nsIMutable.h \
 ../../../../dist/include/xpcom/nsIPropertyBag2.h \
 ../../../../dist/include/xpcom/nsIPropertyBag.h \
 ../../../../dist/include/necko/nsIIDNService.h \
 ../../../../dist/include/necko/nsIURL.h \
 ../../../../dist/include/dom/nsIDOMChromeWindow.h \
 ../../../../dist/include/dom/nsIDOMWindow.h \
 ../../../../dist/include/dom/nsIDOMWindowInternal.h \
 ../../../../dist/include/dom/nsIDOMWindow2.h \
 ../../../../dist/include/dom/nsIDOMEvent.h \
 ../../../../dist/include/dom/nsIDOMEventTarget.h \
 ../../../../dist/include/xpcom/nsAppDirectoryServiceDefs.h \
 ../../../../dist/include/xpcom/nsDirectoryServiceDefs.h \
 ../../../../dist/include/windowwatcher/nsIWindowWatcher.h \
 ../../../../dist/include/appshell/nsIWindowMediator.h \
 ../../../../dist/include/windowwatcher/nsIPromptService.h \
 ../../../../dist/include/pref/nsIPrefBranch.h \
 ../../../../dist/include/pref/nsIPrefService.h \
 ../../../../dist/include/xpcom/nsTArray.h \
 ../../../../dist/include/xpcom/nsQuickSort.h \
 ../../../../dist/include/xpcom/nsVoidArray.h \
 ../../../../dist/include/xpcom/nsEnumeratorUtils.h \
 ../../../../dist/include/necko/nsIFileURL.h \
 ../../../../dist/include/embed_base/nsEmbedCID.h \
 ../../../../dist/include/storage/mozStorageCID.h \
 ../../../../dist/include/storage/mozIStorageService.h \
 ../../../../dist/include/xpcom/nsIMutableArray.h \
 ../../../../dist/include/alerts/nsIAlertsService.h \
 ../../../../dist/include/necko/nsIHttpChannel.h \
 ../../../../dist/include/downloads/nsIDownloadManagerUI.h \
 ../../../../dist/include/necko/nsIResumableChannel.h \
 ../../../../dist/include/exthandler/nsCExternalHandlerService.h \
 ../../../../dist/include/exthandler/nsIExternalHelperAppService.h \
 ../../../../dist/include/exthandler/nsIExternalHelperAppService.h \
 ../../../../dist/include/mimetype/nsIMIMEService.h \
 ../../../../dist/include/parentalcontrols/nsIParentalControlsService.h \
 ../../../../dist/include/toolkitcomps/nsToolkitCompsCID.h \
 ../../../../dist/include/docshell/nsIDownloadHistory.h \
 ../../../../dist/include/docshell/nsDocShellCID.h
