DEPTH   = ../../..
topsrcdir = ../../..
srcdir    = .
VPATH   = .

include $(DEPTH)/config/autoconf.mk

DIRS = public src

ifdef ENABLE_TESTS
DIRS += tests
endif

include $(topsrcdir)/config/rules.mk
