nsGopherChannel.o: nsGopherChannel.cpp /usr/include/stdc-predef.h \
 ../../../../config/gcc_hidden.h ../../../../mozilla-config.h \
 nsGopherChannel.h ../../../base/src/nsBaseChannel.h \
 ../../../../dist/include/string/nsString.h \
 ../../../../dist/include/string/nsSubstring.h \
 ../../../../dist/include/string/nsAString.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/xpcom-config.h \
 ../../../../dist/include/system_wrappers/prtypes.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/nspr/prcpucfg.h \
 ../../../../dist/include/system_wrappers/stddef.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h \
 ../../../../dist/include/nspr/obsolete/protypes.h \
 ../../../../dist/include/system_wrappers/sys/types.h \
 /usr/include/x86_64-linux-gnu/sys/types.h \
 ../../../../dist/include/system_wrappers/features.h \
 /usr/include/features.h \
 ../../../../dist/include/system_wrappers/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/bits/wordsize.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
 /usr/include/x86_64-linux-gnu/bits/types.h \
 /usr/include/x86_64-linux-gnu/bits/typesizes.h \
 ../../../../dist/include/system_wrappers/time.h /usr/include/time.h \
 ../../../../dist/include/system_wrappers/endian.h /usr/include/endian.h \
 /usr/include/x86_64-linux-gnu/bits/endian.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
 ../../../../dist/include/system_wrappers/sys/select.h \
 /usr/include/x86_64-linux-gnu/sys/select.h \
 /usr/include/x86_64-linux-gnu/bits/select.h \
 /usr/include/x86_64-linux-gnu/bits/sigset.h \
 /usr/include/x86_64-linux-gnu/bits/time.h \
 /usr/include/x86_64-linux-gnu/bits/select2.h \
 /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
 /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
 ../../../../dist/include/xpcom/nsError.h \
 ../../../../dist/include/string/nsStringIterator.h \
 ../../../../dist/include/string/nsCharTraits.h \
 ../../../../dist/include/system_wrappers/ctype.h /usr/include/ctype.h \
 /usr/include/xlocale.h ../../../../dist/include/system_wrappers/string.h \
 /usr/include/string.h /usr/include/x86_64-linux-gnu/bits/string3.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/xpcom/nsXPCOM.h \
 ../../../../dist/include/xpcom/nscore.h \
 ../../../../dist/include/xpcom/nsXPCOMCID.h \
 ../../../../dist/include/string/nsAlgorithm.h \
 ../../../../dist/include/string/string-template-def-unichar.h \
 ../../../../dist/include/string/nsTAString.h \
 ../../../../dist/include/string/string-template-undef.h \
 ../../../../dist/include/string/string-template-def-char.h \
 ../../../../dist/include/string/nsSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstringTuple.h \
 ../../../../dist/include/string/nsTSubstring.h \
 ../../../../dist/include/string/nsDependentSubstring.h \
 ../../../../dist/include/string/nsTDependentSubstring.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/system_wrappers/new /usr/include/c++/6/new \
 /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/cpu_defines.h \
 /usr/include/c++/6/exception \
 /usr/include/c++/6/bits/atomic_lockfree_defines.h \
 /usr/include/c++/6/bits/exception_ptr.h \
 /usr/include/c++/6/bits/exception_defines.h \
 /usr/include/c++/6/bits/nested_exception.h \
 /usr/include/c++/6/bits/move.h /usr/include/c++/6/bits/concept_check.h \
 /usr/include/c++/6/type_traits \
 ../../../../dist/include/string/nsTString.h \
 ../../../../dist/include/string/nsDependentString.h \
 ../../../../dist/include/string/nsTDependentString.h \
 ../../../../dist/include/string/nsLiteralString.h \
 ../../../../dist/include/string/nsPromiseFlatString.h \
 ../../../../dist/include/string/nsTPromiseFlatString.h \
 ../../../../dist/include/xpcom/nsMemory.h \
 ../../../../dist/include/xpcom/nsIMemory.h \
 ../../../../dist/include/xpcom/nsISupports.h \
 ../../../../dist/include/xpcom/nsrootidl.h \
 ../../../../dist/include/system_wrappers/prtime.h \
 ../../../../dist/include/nspr/prtime.h \
 ../../../../dist/include/nspr/prlong.h \
 ../../../../dist/include/nspr/prtypes.h \
 ../../../../dist/include/xpcom/nsISupportsBase.h \
 ../../../../dist/include/xpcom/nsID.h \
 ../../../../dist/include/xpcom/nsISupportsUtils.h \
 ../../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../../dist/include/system_wrappers/prthread.h \
 ../../../../dist/include/nspr/prthread.h \
 ../../../../dist/include/nspr/prinrval.h \
 ../../../../dist/include/system_wrappers/pratom.h \
 ../../../../dist/include/nspr/pratom.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/xpcom/nsDebug.h \
 ../../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../../dist/include/xpcom/nsCycleCollector.h \
 ../../../../dist/include/system_wrappers/stdio.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 ../../../../dist/include/system_wrappers/wchar.h /usr/include/wchar.h \
 ../../../../dist/include/system_wrappers/stdarg.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h \
 /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
 /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
 /usr/include/x86_64-linux-gnu/bits/stdio2.h \
 ../../../../dist/include/system_wrappers/plhash.h \
 ../../../../dist/include/nspr/plhash.h \
 ../../../../dist/include/xpcom/nsAutoPtr.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../../dist/include/xpcom/nsHashPropertyBag.h \
 ../../../../dist/include/xpcom/nsCOMArray.h \
 ../../../../dist/include/xpcom/nsVoidArray.h \
 ../../../../dist/include/xpcom/nsStringGlue.h \
 ../../../../dist/include/string/nsReadableUtils.h \
 ../../../../dist/include/xpcom/nsIVariant.h \
 ../../../../dist/include/xpcom/nsIWritablePropertyBag.h \
 ../../../../dist/include/xpcom/nsIPropertyBag.h \
 ../../../../dist/include/xpcom/nsIWritablePropertyBag2.h \
 ../../../../dist/include/xpcom/nsIPropertyBag2.h \
 ../../../../dist/include/xpcom/nsInterfaceHashtable.h \
 ../../../../dist/include/xpcom/nsBaseHashtable.h \
 ../../../../dist/include/xpcom/nsTHashtable.h \
 ../../../../dist/include/xpcom/pldhash.h \
 ../../../../dist/include/system_wrappers/prlock.h \
 ../../../../dist/include/nspr/prlock.h \
 ../../../../dist/include/xpcom/nsHashKeys.h \
 ../../../../dist/include/xpcom/nsIHashable.h \
 ../../../../dist/include/xpcom/nsCRTGlue.h \
 ../../../../dist/include/system_wrappers/stdlib.h \
 /usr/include/c++/6/stdlib.h \
 ../../../../dist/include/system_wrappers/cstdlib \
 /usr/include/c++/6/cstdlib /usr/include/stdlib.h \
 /usr/include/x86_64-linux-gnu/bits/waitflags.h \
 /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
 ../../../../dist/include/system_wrappers/alloca.h /usr/include/alloca.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib.h \
 ../../../base/src/nsInputStreamPump.h \
 ../../../../dist/include/necko/nsIInputStreamPump.h \
 ../../../../dist/include/necko/nsIRequest.h \
 ../../../../dist/include/xpcom/nsIInputStream.h \
 ../../../../dist/include/necko/nsIURI.h \
 ../../../../dist/include/necko/nsILoadGroup.h \
 ../../../../dist/include/necko/nsIStreamListener.h \
 ../../../../dist/include/necko/nsIRequestObserver.h \
 ../../../../dist/include/xpcom/nsIInterfaceRequestor.h \
 ../../../../dist/include/necko/nsIProgressEventSink.h \
 ../../../../dist/include/xpcom/nsIAsyncInputStream.h \
 ../../../../dist/include/xpcom/nsIThread.h \
 ../../../../dist/include/xpcom/nsIEventTarget.h \
 ../../../../dist/include/necko/nsIChannel.h \
 ../../../../dist/include/necko/nsITransport.h \
 ../../../../dist/include/xpcom/nsThreadUtils.h \
 ../../../../dist/include/system_wrappers/prinrval.h \
 ../../../../dist/include/nspr/prinrval.h \
 ../../../../dist/include/xpcom/nsIThreadManager.h \
 ../../../../dist/include/xpcom/nsIThread.h \
 ../../../../dist/include/xpcom/nsIRunnable.h \
 ../../../../dist/include/necko/nsIProxyInfo.h \
 ../../../../dist/include/necko/nsIProxiedChannel.h nsGopherHandler.h \
 ../../../../dist/include/necko/nsIProxiedProtocolHandler.h \
 ../../../../dist/include/necko/nsIProtocolHandler.h \
 ../../../../dist/include/necko/nsIProtocolProxyService.h \
 ../../../base/src/nsBaseContentStream.h \
 ../../../../dist/include/xpcom/nsIEventTarget.h \
 ../../../../dist/include/xpcom/nsIAsyncOutputStream.h \
 ../../../../dist/include/xpcom/nsIOutputStream.h \
 ../../../../dist/include/necko/nsISocketTransportService.h \
 ../../../../dist/include/necko/nsISocketTransport.h \
 ../../../../dist/include/intl/nsIStringBundle.h \
 ../../../../dist/include/xpcom/nsISimpleEnumerator.h \
 ../../../../dist/include/necko/nsITXTToHTMLConv.h \
 ../../../../dist/include/necko/nsIStreamConverter.h \
 ../../../../dist/include/necko/nsIPrompt.h \
 ../../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../../dist/include/xpcom/nsIServiceManagerObsolete.h \
 ../../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../../dist/include/xpcom/nsIFactory.h \
 ../../../../dist/include/xpcom/nsStreamUtils.h \
 ../../../../dist/include/string/nsStringFwd.h \
 ../../../../dist/include/xpcom/nsIInputStream.h \
 ../../../../dist/include/mimetype/nsMimeTypes.h \
 ../../../../dist/include/necko/nsNetCID.h \
 ../../../../dist/include/xpcom/nsEscape.h \
 ../../../../dist/include/xpcom/nsCRT.h \
 ../../../../dist/include/system_wrappers/plstr.h \
 ../../../../dist/include/nspr/plstr.h \
 ../../../../dist/include/xpcom/nsCppSharedAllocator.h \
 ../../../../dist/include/xpcom/nsMemory.h \
 ../../../../dist/include/system_wrappers/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h \
 /usr/include/limits.h /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
 /usr/include/x86_64-linux-gnu/bits/local_lim.h \
 ../../../../dist/include/system_wrappers/linux/limits.h \
 /usr/include/linux/limits.h \
 /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
 /usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
 ../../../../dist/include/system_wrappers/netCore.h \
 ../../../../dist/include/necko/netCore.h \
 ../../../../dist/include/necko/nsNetError.h \
 ../../../../dist/include/xpcom/nsError.h
