nsHTMLEditor.o: nsHTMLEditor.cpp /usr/include/stdc-predef.h \
 ../../../config/gcc_hidden.h ../../../mozilla-config.h \
 ../../../dist/include/layout/nsICaret.h \
 ../../../dist/include/xpcom/nsISupports.h \
 ../../../dist/include/xpcom/nsrootidl.h \
 ../../../dist/include/xpcom/nscore.h \
 ../../../dist/include/xpcom/xpcom-config.h \
 ../../../dist/include/system_wrappers/prtypes.h \
 ../../../dist/include/nspr/prtypes.h \
 ../../../dist/include/nspr/prcpucfg.h \
 ../../../dist/include/system_wrappers/stddef.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stddef.h \
 ../../../dist/include/nspr/obsolete/protypes.h \
 ../../../dist/include/system_wrappers/sys/types.h \
 /usr/include/x86_64-linux-gnu/sys/types.h \
 ../../../dist/include/system_wrappers/features.h /usr/include/features.h \
 ../../../dist/include/system_wrappers/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/sys/cdefs.h \
 /usr/include/x86_64-linux-gnu/bits/wordsize.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs.h \
 /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
 /usr/include/x86_64-linux-gnu/bits/types.h \
 /usr/include/x86_64-linux-gnu/bits/typesizes.h \
 ../../../dist/include/system_wrappers/time.h /usr/include/time.h \
 ../../../dist/include/system_wrappers/endian.h /usr/include/endian.h \
 /usr/include/x86_64-linux-gnu/bits/endian.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap.h \
 /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
 ../../../dist/include/system_wrappers/sys/select.h \
 /usr/include/x86_64-linux-gnu/sys/select.h \
 /usr/include/x86_64-linux-gnu/bits/select.h \
 /usr/include/x86_64-linux-gnu/bits/sigset.h \
 /usr/include/x86_64-linux-gnu/bits/time.h \
 /usr/include/x86_64-linux-gnu/bits/select2.h \
 /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
 /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
 ../../../dist/include/xpcom/nsError.h \
 ../../../dist/include/system_wrappers/prtime.h \
 ../../../dist/include/nspr/prtime.h ../../../dist/include/nspr/prlong.h \
 ../../../dist/include/nspr/prtypes.h \
 ../../../dist/include/xpcom/nsISupportsBase.h \
 ../../../dist/include/xpcom/nsID.h \
 ../../../dist/include/system_wrappers/string.h /usr/include/string.h \
 /usr/include/xlocale.h /usr/include/x86_64-linux-gnu/bits/string3.h \
 ../../../dist/include/xpcom/nsISupportsUtils.h \
 ../../../dist/include/xpcom/nsDebug.h \
 ../../../dist/include/xpcom/nsXPCOM.h \
 ../../../dist/include/xpcom/nsXPCOMCID.h \
 ../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../dist/include/system_wrappers/prthread.h \
 ../../../dist/include/nspr/prthread.h \
 ../../../dist/include/nspr/prinrval.h \
 ../../../dist/include/system_wrappers/pratom.h \
 ../../../dist/include/nspr/pratom.h ../../../dist/include/nspr/prlock.h \
 ../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../dist/include/xpcom/nsCycleCollector.h \
 ../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../dist/include/gfx/nsCoord.h ../../../dist/include/xpcom/nscore.h \
 ../../../dist/include/xpcom/nsMathUtils.h \
 ../../../dist/include/system_wrappers/math.h /usr/include/c++/6/math.h \
 /usr/include/c++/6/cmath \
 /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h \
 /usr/include/x86_64-linux-gnu/c++/6/bits/cpu_defines.h \
 /usr/include/c++/6/bits/cpp_type_traits.h \
 /usr/include/c++/6/ext/type_traits.h /usr/include/math.h \
 /usr/include/x86_64-linux-gnu/bits/math-vector.h \
 /usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h \
 /usr/include/x86_64-linux-gnu/bits/huge_val.h \
 /usr/include/x86_64-linux-gnu/bits/huge_valf.h \
 /usr/include/x86_64-linux-gnu/bits/huge_vall.h \
 /usr/include/x86_64-linux-gnu/bits/inf.h \
 /usr/include/x86_64-linux-gnu/bits/nan.h \
 /usr/include/x86_64-linux-gnu/bits/mathdef.h \
 /usr/include/x86_64-linux-gnu/bits/mathcalls.h \
 ../../../dist/include/system_wrappers/float.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/float.h \
 ../../../dist/include/xpcom/nsDebug.h \
 ../../../dist/include/layout/nsFrameSelection.h \
 ../../../dist/include/layout/nsIFrame.h \
 ../../../dist/include/system_wrappers/stdio.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 ../../../dist/include/system_wrappers/wchar.h /usr/include/wchar.h \
 ../../../dist/include/system_wrappers/stdarg.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdarg.h \
 /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
 /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
 /usr/include/x86_64-linux-gnu/bits/stdio2.h \
 ../../../dist/include/widget/nsEvent.h \
 ../../../dist/include/layout/nsStyleStruct.h \
 ../../../dist/include/gfx/nsColor.h ../../../dist/include/gfx/gfxCore.h \
 ../../../dist/include/gfx/nsMargin.h ../../../dist/include/gfx/nsCoord.h \
 ../../../dist/include/gfx/nsRect.h ../../../dist/include/gfx/nsPoint.h \
 ../../../dist/include/gfx/nsSize.h ../../../dist/include/gfx/nsMargin.h \
 ../../../dist/include/xpcom/nsTraceRefcnt.h \
 ../../../dist/include/gfx/nsFont.h \
 ../../../dist/include/xpcom/nsStringGlue.h \
 ../../../dist/include/string/nsString.h \
 ../../../dist/include/string/nsSubstring.h \
 ../../../dist/include/string/nsAString.h \
 ../../../dist/include/string/nsStringFwd.h \
 ../../../dist/include/string/nsStringIterator.h \
 ../../../dist/include/string/nsCharTraits.h \
 ../../../dist/include/system_wrappers/ctype.h /usr/include/ctype.h \
 ../../../dist/include/string/nsAlgorithm.h \
 ../../../dist/include/string/string-template-def-unichar.h \
 ../../../dist/include/string/nsTAString.h \
 ../../../dist/include/string/string-template-undef.h \
 ../../../dist/include/string/string-template-def-char.h \
 ../../../dist/include/string/nsSubstringTuple.h \
 ../../../dist/include/string/nsTSubstringTuple.h \
 ../../../dist/include/string/nsTSubstring.h \
 ../../../dist/include/string/nsDependentSubstring.h \
 ../../../dist/include/string/nsTDependentSubstring.h \
 ../../../dist/include/string/nsReadableUtils.h \
 ../../../dist/include/system_wrappers/new /usr/include/c++/6/new \
 /usr/include/c++/6/exception \
 /usr/include/c++/6/bits/atomic_lockfree_defines.h \
 /usr/include/c++/6/bits/exception_ptr.h \
 /usr/include/c++/6/bits/exception_defines.h \
 /usr/include/c++/6/bits/nested_exception.h \
 /usr/include/c++/6/bits/move.h /usr/include/c++/6/bits/concept_check.h \
 /usr/include/c++/6/type_traits ../../../dist/include/string/nsTString.h \
 ../../../dist/include/string/nsDependentString.h \
 ../../../dist/include/string/nsTDependentString.h \
 ../../../dist/include/string/nsLiteralString.h \
 ../../../dist/include/string/nsPromiseFlatString.h \
 ../../../dist/include/string/nsTPromiseFlatString.h \
 ../../../dist/include/xpcom/nsMemory.h \
 ../../../dist/include/xpcom/nsIMemory.h \
 ../../../dist/include/system_wrappers/plhash.h \
 ../../../dist/include/nspr/plhash.h \
 ../../../dist/include/string/nsReadableUtils.h \
 ../../../dist/include/xpcom/nsVoidArray.h \
 ../../../dist/include/xpcom/nsStringGlue.h \
 ../../../dist/include/layout/nsStyleCoord.h \
 ../../../dist/include/xpcom/nsCRT.h \
 ../../../dist/include/system_wrappers/stdlib.h \
 /usr/include/c++/6/stdlib.h \
 ../../../dist/include/system_wrappers/cstdlib /usr/include/c++/6/cstdlib \
 /usr/include/stdlib.h /usr/include/x86_64-linux-gnu/bits/waitflags.h \
 /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
 ../../../dist/include/system_wrappers/alloca.h /usr/include/alloca.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
 /usr/include/x86_64-linux-gnu/bits/stdlib.h \
 ../../../dist/include/system_wrappers/plstr.h \
 ../../../dist/include/nspr/plstr.h \
 ../../../dist/include/xpcom/nsCppSharedAllocator.h \
 ../../../dist/include/xpcom/nsMemory.h \
 ../../../dist/include/system_wrappers/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/limits.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed/syslimits.h \
 /usr/include/limits.h /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
 /usr/include/x86_64-linux-gnu/bits/local_lim.h \
 ../../../dist/include/system_wrappers/linux/limits.h \
 /usr/include/linux/limits.h \
 /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
 /usr/include/x86_64-linux-gnu/bits/xopen_lim.h \
 ../../../dist/include/xpcom/nsCRTGlue.h \
 ../../../dist/include/layout/nsStyleConsts.h \
 ../../../dist/include/layout/nsChangeHint.h \
 ../../../dist/include/layout/nsPresContext.h \
 ../../../dist/include/string/nsAString.h \
 ../../../dist/include/layout/nsIPresShell.h \
 ../../../dist/include/layout/nsCompatibility.h \
 ../../../dist/include/layout/nsFrameManagerBase.h \
 ../../../dist/include/xpcom/pldhash.h \
 ../../../dist/include/content/mozFlushType.h \
 ../../../dist/include/xpcom/nsWeakReference.h \
 ../../../dist/include/xpcom/nsIWeakReference.h \
 ../../../dist/include/xpcom/nsIWeakReferenceUtils.h \
 ../../../dist/include/xpcom/nsCOMPtr.h \
 ../../../dist/include/gfx/nsIDeviceContext.h \
 ../../../dist/include/gfx/nsRect.h \
 ../../../dist/include/widget/nsIWidget.h \
 ../../../dist/include/widget/nsEvent.h \
 ../../../dist/include/gfx/nsIRenderingContext.h \
 ../../../dist/include/gfx/nsColor.h \
 ../../../dist/include/thebes/gfxPoint.h \
 ../../../dist/include/thebes/gfxTypes.h \
 ../../../dist/include/xpcom/nsISupportsImpl.h \
 ../../../dist/include/xpcom/nsAutoPtr.h \
 ../../../dist/include/xpcom/nsIWeakReference.h \
 ../../../dist/include/gfx/nsITheme.h \
 ../../../dist/include/locale/nsILanguageAtomService.h \
 ../../../dist/include/xpcom/nsIAtom.h \
 ../../../dist/include/xpcom/nsIObserver.h \
 ../../../dist/include/xpcom/nsITimer.h \
 ../../../dist/include/widget/nsIPrintSettings.h \
 ../../../dist/include/content/nsPropertyTable.h \
 ../../../dist/include/content/nsGkAtoms.h \
 ../../../dist/include/content/nsGkAtomList.h \
 ../../../dist/include/content/nsIDocument.h \
 ../../../dist/include/content/nsINode.h \
 ../../../dist/include/content/nsPIDOMEventTarget.h \
 ../../../dist/include/content/nsPropertyTable.h \
 ../../../dist/include/xpcom/nsTObserverArray.h \
 ../../../dist/include/xpcom/nsTArray.h \
 ../../../dist/include/xpcom/nsQuickSort.h \
 ../../../dist/include/content/nsINodeInfo.h \
 ../../../dist/include/content/nsINameSpaceManager.h \
 ../../../dist/include/content/nsNodeInfoManager.h \
 ../../../dist/include/xpcom/nsCycleCollectionParticipant.h \
 ../../../dist/include/xpcom/nsISupports.h \
 ../../../dist/include/dom/nsDOMString.h \
 ../../../dist/include/content/nsIDocumentObserver.h \
 ../../../dist/include/content/nsIMutationObserver.h \
 ../../../dist/include/xpcom/nsCOMArray.h \
 ../../../dist/include/xpcom/nsVoidArray.h \
 ../../../dist/include/necko/nsIURI.h \
 ../../../dist/include/xpcom/nsWeakPtr.h \
 ../../../dist/include/xpcom/nsIWeakReferenceUtils.h \
 ../../../dist/include/necko/nsILoadGroup.h \
 ../../../dist/include/necko/nsIRequest.h \
 ../../../dist/include/content/mozFlushType.h \
 ../../../dist/include/layout/nsCompatibility.h \
 ../../../dist/include/xpcom/nsInterfaceHashtable.h \
 ../../../dist/include/xpcom/nsBaseHashtable.h \
 ../../../dist/include/xpcom/nsTHashtable.h \
 ../../../dist/include/xpcom/pldhash.h \
 ../../../dist/include/system_wrappers/prlock.h \
 ../../../dist/include/nspr/prlock.h \
 ../../../dist/include/xpcom/nsHashKeys.h \
 ../../../dist/include/xpcom/nsIHashable.h \
 ../../../dist/include/thebes/gfxRect.h \
 ../../../dist/include/thebes/gfxPoint.h \
 ../../../dist/include/layout/nsCSSValue.h \
 ../../../dist/include/layout/nsCSSProperty.h \
 ../../../dist/include/layout/nsCSSPropList.h \
 ../../../dist/include/xpcom/nsCRTGlue.h \
 ../../../dist/include/string/nsStringBuffer.h \
 ../../../dist/include/layout/nsStyleStructFwd.h \
 ../../../dist/include/layout/nsStyleStructList.h \
 ../../../dist/include/layout/nsStyleContext.h \
 ../../../dist/include/layout/nsRuleNode.h \
 ../../../dist/include/content/nsIContent.h \
 ../../../dist/include/content/nsCaseTreatment.h \
 ../../../dist/include/layout/nsChangeHint.h \
 ../../../dist/include/xpcom/nsIProgrammingLanguage.h \
 ../../../dist/include/layout/nsHTMLReflowMetrics.h \
 ../../../dist/include/gfx/nsIRenderingContext.h \
 ../../../dist/include/content/nsISelectionController.h \
 ../../../dist/include/content/nsISelection.h \
 ../../../dist/include/content/nsISelectionDisplay.h \
 ../../../dist/include/layout/nsIScrollableViewProvider.h \
 ../../../dist/include/layout/nsITableLayout.h \
 ../../../dist/include/layout/nsITableCellLayout.h \
 ../../../dist/include/dom/nsIDOMElement.h \
 ../../../dist/include/dom/nsIDOMNode.h \
 ../../../dist/include/dom/domstubs.h \
 ../../../dist/include/widget/nsGUIEvent.h \
 ../../../dist/include/gfx/nsPoint.h \
 ../../../dist/include/dom/nsIDOMKeyEvent.h \
 ../../../dist/include/dom/nsIDOMUIEvent.h \
 ../../../dist/include/dom/nsIDOMEvent.h \
 ../../../dist/include/widget/nsIWidget.h \
 ../../../dist/include/xpcom/nsTArray.h \
 ../../../dist/include/unicharutil/nsUnicharUtils.h nsHTMLEditor.h \
 ../../../editor/libeditor/text/nsPlaintextEditor.h \
 ../../../dist/include/editor/nsIPlaintextEditor.h \
 ../../../dist/include/editor/nsIEditorMailSupport.h \
 ../../../editor/libeditor/base/nsEditor.h \
 ../../../dist/include/editor/nsIEditor.h \
 ../../../dist/include/editor/nsIEditorIMESupport.h \
 ../../../dist/include/content/nsIPhonetic.h \
 ../../../dist/include/widget/nsIKBStateControl.h \
 ../../../dist/include/dom/nsIDOMDocument.h \
 ../../../dist/include/content/nsISelection.h \
 ../../../dist/include/dom/nsIDOMCharacterData.h \
 ../../../dist/include/content/nsIPrivateTextRange.h \
 ../../../dist/include/txmgr/nsITransactionManager.h \
 ../../../dist/include/txmgr/nsITransaction.h \
 ../../../dist/include/txmgr/nsITransactionList.h \
 ../../../dist/include/txmgr/nsITransactionListener.h \
 ../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../dist/include/xpcom/nsIFactory.h \
 ../../../dist/include/editor/nsIEditActionListener.h \
 ../../../dist/include/editor/nsIEditorObserver.h \
 ../../../dist/include/editor/nsIDocumentStateListener.h \
 ../../../dist/include/layout/nsICSSStyleSheet.h \
 ../../../dist/include/layout/nsIStyleSheet.h \
 ../../../editor/libeditor/base/nsSelectionState.h \
 ../../../dist/include/dom/nsIDOMNode.h \
 ../../../dist/include/dom/nsIDOMRange.h \
 ../../../dist/include/editor/nsIEditorSpellCheck.h \
 ../../../dist/include/txtsvc/nsIInlineSpellChecker.h \
 ../../../dist/include/content/nsPIDOMEventTarget.h \
 ../../../dist/include/content/nsStubMutationObserver.h \
 ../../../dist/include/view/nsIViewManager.h \
 ../../../dist/include/view/nsIView.h \
 ../../../dist/include/dom/nsIDOMEventListener.h \
 ../../../editor/libeditor/base/nsEditRules.h \
 ../../../dist/include/editor/nsIHTMLEditor.h \
 ../../../dist/include/editor/nsITableEditor.h \
 ../../../dist/include/editor/nsIEditorStyleSheets.h \
 ../../../dist/include/txtsvc/nsITextServicesDocument.h \
 ../../../dist/include/layout/nsICSSLoader.h \
 ../../../dist/include/string/nsSubstring.h \
 ../../../dist/include/layout/nsICSSLoaderObserver.h \
 ../../../dist/include/layout/nsITableLayout.h \
 ../../../editor/libeditor/base/nsEditProperty.h \
 ../../../editor/libeditor/base/nsEditPropertyAtomList.h nsHTMLCSSUtils.h \
 ../../../dist/include/dom/nsIDOMViewCSS.h \
 ../../../dist/include/dom/nsIDOMAbstractView.h \
 ../../../editor/libeditor/base/ChangeCSSInlineStyleTxn.h \
 ../../../editor/libeditor/base/EditTxn.h \
 ../../../dist/include/txmgr/nsITransaction.h \
 ../../../dist/include/editor/nsPIEditorTransaction.h \
 ../../../dist/include/dom/nsIDOMCSSStyleDeclaration.h \
 nsHTMLObjectResizer.h \
 ../../../dist/include/editor/nsIHTMLObjectResizer.h \
 ../../../dist/include/dom/nsIDOMMouseEvent.h \
 ../../../dist/include/content/nsISelectionListener.h \
 ../../../dist/include/dom/nsIDOMMouseMotionListener.h \
 ../../../dist/include/dom/nsIDOMEventListener.h \
 ../../../dist/include/editor/nsIHTMLAbsPosEditor.h \
 ../../../dist/include/editor/nsIHTMLInlineTableEditor.h \
 ../../../dist/include/editor/nsIHTMLObjectResizeListener.h \
 ../../../dist/include/content/nsIDocumentObserver.h nsHTMLEditRules.h \
 ../../../editor/libeditor/text/nsTextEditRules.h \
 ../../../editor/libeditor/text/nsPlaintextEditor.h nsIHTMLEditRules.h \
 ../../../editor/libeditor/base/nsEditorUtils.h \
 ../../../editor/libeditor/base/nsEditor.h \
 ../../../dist/include/content/nsIContentIterator.h TypeInState.h \
 ../../../editor/libeditor/text/nsTextEditUtils.h \
 ../../../dist/include/xpcom/nsError.h nsHTMLEditUtils.h \
 ../../../editor/libeditor/text/nsEditorEventListeners.h \
 ../../../dist/include/dom/nsIDOMEvent.h \
 ../../../dist/include/dom/nsIDOMKeyListener.h \
 ../../../dist/include/dom/nsIDOMMouseListener.h \
 ../../../dist/include/dom/nsIDOMTextListener.h \
 ../../../dist/include/dom/nsIDOMDragListener.h \
 ../../../dist/include/dom/nsIDOMCompositionListener.h \
 ../../../dist/include/dom/nsIDOMFocusListener.h \
 ../../../dist/include/layout/nsIPresShell.h nsHTMLEditorMouseListener.h \
 nsHTMLURIRefObject.h ../../../dist/include/editor/nsIURIRefObject.h \
 ../../../dist/include/dom/nsIDOMNamedNodeMap.h \
 ../../../dist/include/dom/nsIDOMText.h \
 ../../../dist/include/dom/nsIDOMNodeList.h \
 ../../../dist/include/dom/nsIDOMAttr.h \
 ../../../dist/include/dom/nsIDOMEventTarget.h \
 ../../../dist/include/dom/nsIDOM3EventTarget.h \
 ../../../dist/include/content/nsISelectionPrivate.h \
 ../../../dist/include/xpcom/nsIEnumerator.h \
 ../../../dist/include/xpcom/nsISimpleEnumerator.h \
 ../../../dist/include/dom/nsIDOMHTMLAnchorElement.h \
 ../../../dist/include/dom/nsIDOMHTMLElement.h \
 ../../../dist/include/dom/nsIDOMHTMLHtmlElement.h \
 ../../../dist/include/dom/nsIDOMEventGroup.h \
 ../../../dist/include/webshell/nsILinkHandler.h \
 ../../../editor/libeditor/base/TransactionFactory.h \
 ../../../dist/include/dom/nsIDOMStyleSheet.h \
 ../../../dist/include/dom/nsIDOMNSRange.h \
 ../../../dist/include/content/nsIRangeUtils.h \
 ../../../dist/include/xpcom/nsISupportsArray.h \
 ../../../dist/include/xpcom/nsICollection.h \
 ../../../dist/include/xpcom/nsISerializable.h \
 ../../../dist/include/content/nsContentUtils.h \
 ../../../dist/include/js/jspubtd.h ../../../dist/include/js/jstypes.h \
 ../../../dist/include/js/jsautocfg.h ../../../dist/include/js/jsotypes.h \
 ../../../dist/include/js/jscompat.h ../../../dist/include/js/jslong.h \
 ../../../dist/include/js/jsproto.tbl ../../../dist/include/js/jsconfig.h \
 ../../../dist/include/js/jsnum.h \
 ../../../dist/include/layout/nsIStatefulFrame.h \
 ../../../dist/include/pref/nsIPref.h \
 ../../../dist/include/pref/nsIPrefService.h \
 ../../../dist/include/pref/nsIPrefBranch.h \
 ../../../dist/include/content/nsContentList.h \
 ../../../dist/include/dom/nsIDOMHTMLCollection.h \
 ../../../dist/include/content/nsStubMutationObserver.h \
 ../../../dist/include/dom/nsDOMClassInfoID.h \
 ../../../dist/include/xpcom/nsIClassInfo.h \
 ../../../dist/include/dom/nsIDOM3Node.h \
 ../../../dist/include/xpcom/nsDataHashtable.h \
 ../../../dist/include/dom/nsIScriptRuntime.h \
 ../../../dist/include/dom/nsIScriptContext.h \
 ../../../dist/include/dom/nsIScriptGlobalObject.h \
 ../../../dist/include/necko/nsIURL.h \
 ../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../dist/include/xpcom/nsIServiceManager.h \
 ../../../dist/include/xpcom/nsIServiceManagerObsolete.h \
 ../../../dist/include/xpcom/nsIComponentManager.h \
 ../../../dist/include/content/nsIDocumentEncoder.h \
 ../../../dist/include/dom/nsIDOMDocumentFragment.h \
 ../../../dist/include/layout/nsPresContext.h \
 ../../../dist/include/gfx/nsIImage.h \
 ../../../editor/libeditor/text/nsAOLCiter.h \
 ../../../dist/include/editor/nsICiter.h \
 ../../../editor/libeditor/text/nsInternetCiter.h \
 ../../../dist/include/xpcom/nsXPCOM.h \
 ../../../dist/include/xpcom/nsISupportsPrimitives.h \
 ../../../editor/libeditor/base/SetDocTitleTxn.h \
 ../../../dist/include/content/nsTextFragment.h \
 ../../../dist/include/necko/nsNetUtil.h \
 ../../../dist/include/necko/nsNetError.h \
 ../../../dist/include/necko/nsNetCID.h \
 ../../../dist/include/system_wrappers/prio.h \
 ../../../dist/include/nspr/prio.h ../../../dist/include/nspr/prtime.h \
 ../../../dist/include/nspr/prinet.h \
 ../../../dist/include/system_wrappers/sys/socket.h \
 /usr/include/x86_64-linux-gnu/sys/socket.h \
 ../../../dist/include/system_wrappers/sys/uio.h \
 /usr/include/x86_64-linux-gnu/sys/uio.h \
 /usr/include/x86_64-linux-gnu/bits/uio.h \
 /usr/include/x86_64-linux-gnu/bits/socket.h \
 /usr/include/x86_64-linux-gnu/bits/socket_type.h \
 /usr/include/x86_64-linux-gnu/bits/sockaddr.h \
 /usr/include/x86_64-linux-gnu/asm/socket.h \
 /usr/include/asm-generic/socket.h \
 /usr/include/x86_64-linux-gnu/asm/sockios.h \
 /usr/include/asm-generic/sockios.h \
 /usr/include/x86_64-linux-gnu/bits/socket2.h \
 ../../../dist/include/system_wrappers/netinet/in.h \
 /usr/include/netinet/in.h ../../../dist/include/system_wrappers/stdint.h \
 /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h /usr/include/stdint.h \
 /usr/include/x86_64-linux-gnu/bits/wchar.h \
 /usr/include/x86_64-linux-gnu/bits/in.h \
 ../../../dist/include/system_wrappers/arpa/inet.h \
 /usr/include/arpa/inet.h ../../../dist/include/system_wrappers/netdb.h \
 /usr/include/netdb.h /usr/include/rpc/netdb.h \
 /usr/include/x86_64-linux-gnu/bits/siginfo.h \
 /usr/include/x86_64-linux-gnu/bits/netdb.h \
 ../../../dist/include/necko/nsIURI.h \
 ../../../dist/include/xpcom/nsIInputStream.h \
 ../../../dist/include/xpcom/nsIOutputStream.h \
 ../../../dist/include/necko/nsISafeOutputStream.h \
 ../../../dist/include/necko/nsIStreamListener.h \
 ../../../dist/include/necko/nsIRequestObserver.h \
 ../../../dist/include/necko/nsIRequestObserverProxy.h \
 ../../../dist/include/necko/nsISimpleStreamListener.h \
 ../../../dist/include/necko/nsILoadGroup.h \
 ../../../dist/include/xpcom/nsIInterfaceRequestor.h \
 ../../../dist/include/xpcom/nsIInterfaceRequestorUtils.h \
 ../../../dist/include/necko/nsIIOService.h \
 ../../../dist/include/necko/nsIChannel.h \
 ../../../dist/include/necko/nsIInputStreamChannel.h \
 ../../../dist/include/necko/nsITransport.h \
 ../../../dist/include/necko/nsIStreamTransportService.h \
 ../../../dist/include/necko/nsIHttpChannel.h \
 ../../../dist/include/necko/nsIDownloader.h \
 ../../../dist/include/necko/nsIStreamLoader.h \
 ../../../dist/include/necko/nsIUnicharStreamLoader.h \
 ../../../dist/include/xpcom/nsIPipe.h \
 ../../../dist/include/xpcom/nsIAsyncInputStream.h \
 ../../../dist/include/xpcom/nsIAsyncOutputStream.h \
 ../../../dist/include/necko/nsIProtocolHandler.h \
 ../../../dist/include/necko/nsIFileProtocolHandler.h \
 ../../../dist/include/xpcom/nsIStringStream.h \
 ../../../dist/include/xpcom/nsILocalFile.h \
 ../../../dist/include/xpcom/nsIFile.h \
 ../../../dist/include/xpcom/nsDirectoryServiceUtils.h \
 ../../../dist/include/xpcom/nsIProperties.h \
 ../../../dist/include/system_wrappers/prlink.h \
 ../../../dist/include/nspr/prlink.h \
 ../../../dist/include/necko/nsIFileStreams.h \
 ../../../dist/include/necko/nsIProtocolProxyService.h \
 ../../../dist/include/necko/nsIProxyInfo.h \
 ../../../dist/include/necko/nsIBufferedStreams.h \
 ../../../dist/include/necko/nsIInputStreamPump.h \
 ../../../dist/include/necko/nsIAsyncStreamCopier.h \
 ../../../dist/include/xpcom/nsIPersistentProperties2.h \
 ../../../dist/include/necko/nsISyncStreamListener.h \
 ../../../dist/include/xpcom/nsInterfaceRequestorAgg.h \
 ../../../dist/include/xpcom/nsIInterfaceRequestor.h \
 ../../../dist/include/xpcom/nsInt64.h \
 ../../../dist/include/system_wrappers/prlong.h \
 ../../../dist/include/nspr/prlong.h \
 ../../../dist/include/necko/nsINetUtil.h \
 ../../../dist/include/necko/nsIAuthPrompt.h \
 ../../../dist/include/necko/nsIAuthPrompt2.h \
 ../../../dist/include/necko/nsIAuthPromptAdapterFactory.h \
 ../../../dist/include/xpcom/nsComponentManagerUtils.h \
 ../../../dist/include/xpcom/nsServiceManagerUtils.h \
 ../../../dist/include/necko/nsINestedURI.h \
 ../../../dist/include/xpcom/nsIMutable.h \
 ../../../dist/include/xpcom/nsIPropertyBag2.h \
 ../../../dist/include/xpcom/nsIPropertyBag.h \
 ../../../dist/include/necko/nsIIDNService.h \
 ../../../dist/include/widget/nsIClipboard.h \
 ../../../dist/include/widget/nsITransferable.h \
 ../../../dist/include/widget/nsIFormatConverter.h \
 ../../../dist/include/widget/nsIClipboardOwner.h \
 ../../../dist/include/widget/nsITransferable.h \
 ../../../dist/include/widget/nsIDragService.h \
 ../../../dist/include/widget/nsIDragSession.h \
 ../../../dist/include/gfx/nsSize.h \
 ../../../dist/include/gfx/nsIScriptableRegion.h \
 ../../../dist/include/dom/nsIDOMNSUIEvent.h \
 ../../../dist/include/editor/nsIContentFilter.h \
 ../../../editor/libeditor/base/nsStyleSheetTxns.h TextEditorTest.h \
 nsWSRunObject.h ../../../dist/include/layout/nsIFrame.h \
 ../../../dist/include/view/nsIView.h \
 ../../../dist/include/htmlparser/nsIParserService.h \
 ../../../dist/include/htmlparser/nsHTMLTags.h \
 ../../../dist/include/htmlparser/nsHTMLTagList.h \
 ../../../dist/include/htmlparser/nsIElementObserver.h \
 ../../../dist/include/content/nsIEventStateManager.h
